name: Tests

on: [push, pull_request]

jobs:
  test:
    name: JS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Cache yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        shell: bash
        run: |
          set -eux
          npm install -g yarn
          yarn

      - name: Build Source
        shell: bash
        run: |
            set -eux
            yarn build
            yarn build:test

      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            yarn test

      - name: Test Examples
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          set -eux
          yarn minimize
          yarn build:examples
          yarn test:examples

      - name: Build Docs
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          set -eux
          yarn clean
          yarn docs

      - name: Publish with Verdaccio
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          set -eux
          if [ ! -z ${GITHUB_HEAD_REF} ]; then
            export BRANCH=${GITHUB_HEAD_REF}
          else
            # e.g refs/head/foo or refs/tag/bar
            export BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3)
          fi
          git fetch origin $BRANCH
          git checkout $BRANCH
          npm install -g verdaccio
          verdaccio --config .github/scripts/verdaccio.yml &
          npm set registry http://localhost:4873/
          yarn config set registry http://localhost:4873/
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          yarn run version patch --no-push --yes
          yarn run publish
